use crate::build_utils::handler_updater::HandlerRouteInfo;
use anyhow::Result;
use std::fs;
use std::path::Path;
use std::collections::BTreeSet;

/// Generates a central OpenAPI definition file based on discovered handlers
pub fn generate_openapi_spec(
    project_root: &Path,
    handlers: &[HandlerRouteInfo],
) -> Result<()> {
    let mut submodules = Vec::new();
    let mut paths_list = Vec::new();
    let mut schemas_list = BTreeSet::new();

    for (i, handler) in handlers.iter().enumerate() {
        let mod_alias = format!("handler_mod_{}", i);
        // CRITICAL: We MUST re-export both the handler function AND the hidden __path_ struct
        // This is the clean way to handle utoipa naming collisions without renaming functions
        submodules.push(format!(
            "mod {} {{ pub use {}::{}; pub use {}::__path_{}; }}",
            mod_alias, handler.handler_module_path, handler.func_name,
            handler.handler_module_path, handler.func_name
        ));
        paths_list.push(format!("{}::{},", mod_alias, handler.func_name));
        
        for schema in &handler.discovered_schemas {
            schemas_list.insert(schema.clone());
        }
    }

    // Core schemas
    schemas_list.insert("crate::core::types::ApiResponse<String>".to_string());

    let schemas_code: Vec<String> = schemas_list.into_iter().map(|s| format!("{},", s)).collect();

    let generated_content = format!(
        r#"#![allow(unused_imports)]
/// THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
/// DO NOT EDIT THIS FILE MANUALLY

use utoipa::OpenApi;

{}

#[derive(OpenApi)]
#[openapi(
    paths(
        {}
    ),
    components(
        schemas(
            {}
        )
    ),
    tags(
        (name = "api", description = "Auto-generated API endpoints")
    )
)]
pub struct GeneratedApiDoc;
"#,
        submodules.join("\n"),
        paths_list.join("\n        "),
        schemas_code.join("\n            ")
    );

    let output_path = project_root.join("src/observability/openapi_generated.rs");
    
    // Ensure parent directory exists
    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent)?;
    }

    fs::write(output_path, generated_content)?;
    
    Ok(())
}
