/// THIS FILE IS AUTOMATICALLY GENERATED BY build.rs
/// DO NOT EDIT THIS FILE MANUALLY

pub mod anime2;
pub mod anime;
pub mod komik;
pub mod proxy;
pub mod tools;

/// Register routes for this directory
use axum::Router;
use std::sync::Arc;
use crate::routes::AppState;

pub fn register_routes(router: Router<Arc<AppState>>) -> Router<Arc<AppState>> {
    anime::register_routes(anime2::register_routes(komik::register_routes(proxy::register_routes(tools::register_routes(router)))))
}
